sudo: false
language: python

python:
  - '2.7'

install:
  - pip install tox

env:
  - TOX_ENV=py27-test
  - TOX_ENV=py33-test
  - TOX_ENV=py34-test
  - TOX_ENV=py35-test
  - TOX_ENV=py36-test

script:
  - tox -e $TOX_ENV

deploy:
  provider: pypi
  user: onefinestay
  password:
    secure: L838z+MtH79Px67frLMPo1LP/FULLDDlx6SOgZ/Npg+NBAs8D+Yu2OGCSLxgaHUU7FqK0Gqp4NNQxM8yLD1mGPbtgyd/DYlL8ugDHu45QEx+7YI2tAwc6XOKba1PXqYZi33/aCDUe5LYcVKfoNqXaXZxt25eWwI1VjnH5KJdEpI=
  on:
    tags: true
    repo: onefinestay/nameko-sqlalchemy
